version: '3.8'

services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: charity_db_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db_backup.dump:/db_backup.dump
    ports:
      - "5433:5432"
    networks:
      - charity-net # ƒê∆∞a v√†o m·∫°ng chung

  api:
    image: postgrest/postgrest
    restart: always
    environment:
      PGRST_DB_URI: "postgres://postgres:password@db:5432/charity_db_v2"
      PGRST_DB_SCHEMA: "public"
      PGRST_DB_ANON_ROLE: "web_anon"
      PGRST_JWT_SECRET: "secret_keysecret_keysecret_keysecret_keysecret_key"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - charity-net # ƒê∆∞a v√†o m·∫°ng chung

  prometheus-charity:
    image: prom/prometheus:latest
    container_name: prometheus-charity
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - charity-net # ƒê∆∞a v√†o m·∫°ng chung

  grafana-charity:
    image: grafana/grafana:11.0.0
    container_name: grafana-charity
    ports:
      - "4000:4000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_SERVER_HTTP_PORT=4000
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus-charity
    restart: unless-stopped
    networks:
      - charity-net # ƒê∆∞a v√†o m·∫°ng chung
  
  # D·ªãch v·ª• APM: Zipkin
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    ports:
      - "9411:9411"
    networks:
      - charity-net # ƒê∆∞a v√†o m·∫°ng chung


  zookeeper-charity:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper-charity
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      # üåü B·ªï sung: ID Server l√† c·∫ßn thi·∫øt
      ZOOKEEPER_SERVER_ID: 1 
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - charity-net 

  kafka-charity:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-charity
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-charity:2181 
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      
      KAFKA_LISTENERS: PLAINTEXT://kafka-charity:29092,EXTERNAL://0.0.0.0:9092
      
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-charity:29092,EXTERNAL://localhost:9092
      
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT 
      
    depends_on:
      - zookeeper-charity
    networks:
      - charity-net

volumes:
  prom_data:
  grafana_data: 

networks:
  charity-net: # ƒê·ªãnh nghƒ©a m·∫°ng chung cho t·∫•t c·∫£ c√°c services
    driver: bridge